### ISSUE TITLE
add the CI to test the scripts which produces the proper output

### ISSUE THREAD

**Issue by rustiever** [rustiever/Hello-World#3]

**Comment by coryallegory** [comment]
Would this mean add automated testing to verify the scripts each output hello world? Not sure of what is meant by Delivery in the case of this repo as I understand it.

**Comment by rustiever** [comment]
yes what you meant is absolutely correct. CI is for testing whether each script produces the hello world as output

**Comment by rustiever** [comment]
closing for now
